### ISSUE TITLE
Bump graceful-fs dependency

### ISSUE THREAD

**Issue by ChALkeR** [jspm/registry-endpoint#11]
`graceful-fs` versions lower than v4 reevaluate native `fs` module source, which is not supported.
You should update your `graceful-fs` dependency to v4 or later. 

Tracking issue: https://github.com/nodejs/node/issues/5213.

**Comment by guybedford** [comment]
https://github.com/jspm/registry-endpoint/commit/7aa8c5980215fb122c0bbea4300d32295114f97a
