### ISSUE TITLE
Windows UNC paths cause git error

### ISSUE THREAD

**Issue by peta** [jspm/registry-endpoint#13]
The default windows shell (cmd.exe) doesn't support UNC network paths (`\\path\to\network\share`) and because *jspm-registry* git clones the configured registry repository by dropping a shell command line, it breaks when `registries.jspm.repo` is set to an absolute UNC directory path.

However, there's an easy solution: replacing all backslashes with normal slashes.

Replacing the method body at https://github.com/jspm/registry-endpoint/blob/master/registry.js#L155 fixes this:

```js
// Default windows shell doesn't support UNC paths => escape it
var repo = self.repo;
if (process.platform == 'win32' && (/^[\\\/]{2,}[^\\\/]+[\\\/]+[^\\\/]+/).test(repo)) repo = repo.replace(/\\/, '/');
return asp(exec)('git clone --depth=1 ' + repo + ' .', self.execOptions);
```

**Comment by guybedford** [comment]
Thanks for working this out, that makes sense. Can you send a PR?

**Comment by gcnm-pgeil** [comment]
Yep, on its way...

**Comment by peta** [comment]
@guybedford See pull request here: https://github.com/jspm/registry-endpoint/pull/14
