### ISSUE TITLE
git remote show origin error string doesn't match expected

### ISSUE THREAD

**Issue by mmilbrath** [jspm/registry-endpoint#17]
https://github.com/jspm/registry-endpoint/commit/a8cfa5ee386affcb2d78bc412aff41fdba932dba#diff-The error string search was recently updated in commit 62f43d4ae581a9c928a4099378663e34 and we've suddenly run into an issue where things are breaking.

I traced it down to this commit and on our linux hosts (using git version 1.8.3.1) the error message printed out is illustrated below so the updated version isn't calling self.createRegistry().

I haven't analyzed newer versions of GIT yet to see if error string is different but wanted to see if there was a recommendation or other suggestions?

Illustrative error message from this area of code when using Git 1.8.3.1
...
registry error Error: Command failed: /bin/sh -c git remote show origin -n
fatal: Not a git repository (or any parent up to mount point /disk1)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
...

Thanks

**Comment by guybedford** [comment]
Thanks, I've altered the check here and posted a 0.4.3. Just let me know if you're still getting an issue here at all.
