### ISSUE TITLE
Error creating registry file

### ISSUE THREAD

**Issue by fodonnel** [jspm/registry-endpoint#9]
When running jspm install on Windows 8.1 I get the following error:

Error creating registry file
Error: Command failed: C:\windows\system32\cmd.exe /s /c "git clone --depth
tps://github.com/jspm/registry.git ."
fatal: destination path '.' already exists and is not an empty directory.

The problem seems to be in 
https://github.com/jspm/registry-endpoint/blob/master/registry.js
Line 155: return asp(exec)('git clone --depth=1 ' + self.repo + ' .', self.execOptions);

I am not sure what you expect the working directory will be once you run the cmd /s command, put on my machine (in a corporate env) the working directory is always H:\

So i have  a prompt on c:\ and I run cmd /s -  it opens on h:\

self.registryPath is C:\Users\User1\AppData\Local\.jspm\jspm-cache

I hacked that line of the script on my box to read: 
return asp(exec)('git clone --depth=1 ' + self.repo + ' ' + path.resolve(self.registryPath), self.execOptions);

Which seems to work.

**Comment by guybedford** [comment]
Thanks so much for the detailed feedback, helps a lot. So it's supposed to clone into the temporary directory set in https://github.com/jspm/registry-endpoint/blob/master/registry.js#L24. If you can you confirm the value of `execOptions.tmpDir` on your machine, that would help a lot to work out why it's not accepting it. Also did you try running a cache clear via `jspm cc`?

**Comment by fodonnel** [comment]
yes i have run  jspm cc, I also tried clearing out the tmp folder, running as admin, running in powershell and reinstalling node

The options object has the following:

options at line 23 has
* timeouts: [object Object]
* tmpDir: C:\Users\User1\AppData\Local\\.jspm\jspm-cache
* apiVersion: 1.0
* handler: jspm-registry
* remote: https://registry.jspm.io
* name: jspm
* versionString: jspm-registry@0.4

options.timeouts:
* lookup: undefined
* download: undefined
* build: undefined

execOptions at line 155 has:
* cwd: C:\Users\User1\AppData\Local\\.jspm\jspm-cache
* timeout: NaN
* killSignal: SIGKILL

Versions I have installed
* node -v: v0.12.40
* npm -v: 2.10.1
* jspm -v: 0.15.6 (Running against global jspm install.)

Some of windows env variables that might be useful
* echo %TEMP% : C:\Users\User1\AppData\Local\Temp
* echo %TMP% : C:\Users\User1\AppData\Local\Temp
* echo %HOME% : %HOME%
* echo %USERPROFILE% :  C:\Users\User1
* echo %HOMEPATH% :  \

**Comment by fodonnel** [comment]
It looks like my problem is with the node child_process module, not jspm

When my working directory is c:\windows and I run the following script, it lists the content of H:\ twice instead of c:\windows

var exec = require('child_process').exec;
exec('dir', function(error, stdout, stderr) {
    console.log('stdout: ' + stdout);
});

exec('dir', { cwd: 'C:/windows' }, function(error, stdout, stderr) {
    console.log('stdout: ' + stdout);
});

I will have a look through the that module and raise a bug with them
Thanks for you help

**Comment by fodonnel** [comment]
FYI - My problem was that the cmd had a autorun registry setting:

HKEY_LOCAL_MACHINE\Software\Microsoft\Command Processor\AutoRun
It was set to: cd /d H:\

Thanks!
